---
title: "R Shiny + DiagrammeR"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE, warning=FALSE}
library(shiny)
library(shinyAce)
library(DiagrammeR)
library(htmlwidgets)
library(devtools)
library(rsconnect)
```

```{r}
diagram =
"digraph boxes {

  # a 'graph' statement above ??? I actually do not know what func it is
  graph [overlap = true, fontsize = 10]

  # several 'node' statements
  node [shape = egg,
        fontname = Helvetica]
  Title [fillcolor = 'grey']

  node [shape = egg, 
        color = black, 
        fillcolor = grey] 
  a; b

  node [shape = egg] 
  1; 2

  node [shape = egg] 
  3; 4

  # several 'edge' statements
  Title -> {a b}
  [arrowhead = 'dot']
  a-> {1 2}
  [arrowhead = 'dot']
  b-> {3, 4}
  [arrowhead = 'dot']
}
"
# Shiny app
server <- function(input, output) {
  output$diagram <- renderGrViz({
    grViz({
      diagram
    })
  })
}

ui <- fluidPage(
  grVizOutput('diagram', width = "100%", height = "760px") 
)

shinyApp(ui = ui, server = server)
```
