---
title: "Var Relationships"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
library(DiagrammeR)
```

Variable names
```{r}
pi = "$\\\\pi$"
```

Diagram

```{r echo=FALSE}
add_mathjax(
  grViz(
"
digraph relationship {

# node definitions with substituted label text
node [fontname = Helvetica, shape = box]
NPV [label = '$NPV (1) $']## label indicates the position of the letter

node [fontname = Helvetica, shape = box, fontsize = 10, fixedsize = TRUE]
B [label = '$B (2)$']
C [label = '$C (10)$']

node [fontname = Helvetica, shape = box, fixedsize = TRUE]
r [label = '$r (3)$']
Et [label = '$E_t (4)$']
DC [label = '$DC (11)$']
IC [label = '$IC (??)$']

node [fontname = Helvetica, shape = box, fixedsize = TRUE]
g [label = '$g$']
pi [label = '$\\\\pi$']
wt [label = '$w_t (5)$']
lambda1 [label = '$\\\\lambda_1 (8)$']
lambda2 [label = '$\\\\lambda_2$']
p [label = '$p (9)$']
R [label = '$R$']

S1 [label = '$S_1$']
QS1 [label = '$Q(S_1)$']
S2 [label = '$S_2$']
QS2 [label = '$Q(S_2)$']

K [label = '$K$']

node [fontname = Helvetica, shape = box, fixedsize = FALSE]
DeltaEt [label = '$\\\\Delta\\\\bar{E_t}(S_1, S_2)$']

node [fontname = Helvetica, shape = box, fixedsize = TRUE]
w0 [label = '$w_0$']
Xp [label = '$X_p$']
beta1 [label = '$\\\\hat{\\\\beta_1}$']
beta2 [label = '$\\\\hat{\\\\beta_2}$']
lambda1m [label = '$\\\\lambda_{1, male}$']
lambda1f [label = '$\\\\lambda_{1, female}$']
R [label = '$R$']
Qfull [label = '$Q(full)$']
Q0 [label = '$Q(0)$']

# edge definitions with the node IDs
NPV -> {B C}       ##[label = ...] adds text on the edge
B -> {r Et} 
C -> {DC IC} 
r -> {g pi} 
Et -> {wt lambda1 lambda2 p R} 
DC -> {S1 QS1 S2 QS2} 
IC -> {K r DeltaEt}
wt -> {w0 g Xp beta1 beta2}
lambda1 -> {lambda1m lambda1f}
p -> {R Qfull Q0}
}
")
)
```

